---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - shopops.shopops.dc.com
  resources:
  - discordchannels
  - shops
  - wallets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - shopops.shopops.dc.com
  resources:
  - discordchannels/finalizers
  - shops/finalizers
  - wallets/finalizers
  verbs:
  - update
- apiGroups:
  - shopops.shopops.dc.com
  resources:
  - discordchannels/status
  - shops/status
  - wallets/status
  verbs:
  - get
  - patch
  - update
