apiVersion: shopops.shopops.dc.com/v1
kind: Shop
metadata:
  labels:
    app.kubernetes.io/name: shop-operator
    app.kubernetes.io/managed-by: kustomize
  name: shop-sample
spec:
  # TODO(user): Add fields here
