apiVersion: shopops.shopops.dc.com/v1
kind: DiscordChannel
metadata:
  labels:
    app.kubernetes.io/name: shop-operator
    app.kubernetes.io/managed-by: kustomize
  name: discordchannel-sample
spec:
  # TODO(user): Add fields here
