apiVersion: shopops.shopops.dc.com/v1
kind: Shop
metadata:
  labels:
    app.kubernetes.io/name: shop-operator
    app.kubernetes.io/managed-by: kustomize
  name: shop-sample
spec:
  name: Sample Shop
  availability: standard
  walletAddress: 0x1111111111111111111111111111111111111111
  database:
    type: standard
  image: nginx:latest
  host: shop.example.com
  discordChannelRef: shop-alerts
